{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context-support",
    "version": "6.2.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.2.3.jar",
          "url": "spring-context-support-6.2.3.jar",
          "size": 175199,
          "sha512": "2687b6a591d2f92f8e6a7979b73188ad5e4b9ef688ce31c6a6ed047b88bd213960080d379f1fc38b74e81985fcfbb314af67f6fc06a23b4e6970ff14c2403d29",
          "sha256": "e8853046c113b3b789eda52b946a9323aef1ea2f569a313bf158fac5554bd986",
          "sha1": "4b03d0d4735ac68dbca8953b4e5cae4b1997e3b1",
          "md5": "2768aef1cdfec630ca44c94090d71989"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.2.3.jar",
          "url": "spring-context-support-6.2.3.jar",
          "size": 175199,
          "sha512": "2687b6a591d2f92f8e6a7979b73188ad5e4b9ef688ce31c6a6ed047b88bd213960080d379f1fc38b74e81985fcfbb314af67f6fc06a23b4e6970ff14c2403d29",
          "sha256": "e8853046c113b3b789eda52b946a9323aef1ea2f569a313bf158fac5554bd986",
          "sha1": "4b03d0d4735ac68dbca8953b4e5cae4b1997e3b1",
          "md5": "2768aef1cdfec630ca44c94090d71989"
        }
      ]
    }
  ]
}
