{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-mail",
    "version": "3.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.eclipse.angus",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-mail-3.4.3.jar",
          "url": "spring-boot-starter-mail-3.4.3.jar",
          "size": 4774,
          "sha512": "c95febce381c94317ec3c38d0193333782aaeaa3b8f068e25b2696f7d83cbf6c5a2868b45eeda60caa2314c6132dcf36d0251040959a0b4b85f10f83f606dd4d",
          "sha256": "eadef390e5c30e7d8bab340c5171a016f0fe8fddaa0c464409855de77f5317c2",
          "sha1": "e9f326755180984e7166c829c48552f12762e596",
          "md5": "fb6e9264f4e4e96aa64b2e283adfa17e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context-support",
          "version": {
            "requires": "6.2.3"
          }
        },
        {
          "group": "org.eclipse.angus",
          "module": "jakarta.mail",
          "version": {
            "requires": "2.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-mail-3.4.3.jar",
          "url": "spring-boot-starter-mail-3.4.3.jar",
          "size": 4774,
          "sha512": "c95febce381c94317ec3c38d0193333782aaeaa3b8f068e25b2696f7d83cbf6c5a2868b45eeda60caa2314c6132dcf36d0251040959a0b4b85f10f83f606dd4d",
          "sha256": "eadef390e5c30e7d8bab340c5171a016f0fe8fddaa0c464409855de77f5317c2",
          "sha1": "e9f326755180984e7166c829c48552f12762e596",
          "md5": "fb6e9264f4e4e96aa64b2e283adfa17e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-mail-3.4.3-javadoc.jar",
          "url": "spring-boot-starter-mail-3.4.3-javadoc.jar",
          "size": 4774,
          "sha512": "c95febce381c94317ec3c38d0193333782aaeaa3b8f068e25b2696f7d83cbf6c5a2868b45eeda60caa2314c6132dcf36d0251040959a0b4b85f10f83f606dd4d",
          "sha256": "eadef390e5c30e7d8bab340c5171a016f0fe8fddaa0c464409855de77f5317c2",
          "sha1": "e9f326755180984e7166c829c48552f12762e596",
          "md5": "fb6e9264f4e4e96aa64b2e283adfa17e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-mail-3.4.3-sources.jar",
          "url": "spring-boot-starter-mail-3.4.3-sources.jar",
          "size": 4774,
          "sha512": "92e9dc6ef0c288f5033568dc75a0ad46883035a9fe2945888472ab9b0c3a53998d3a24be554fab4ec7c3bf250220ac91f56f783a64c93ae275c3bc83d6a00840",
          "sha256": "088c46a276270e0da256f13aaf6aaf4a29ed0b447c3bad2d2490f30e87ac454d",
          "sha1": "62a0cac6efc76c430dbe7a7c6edf50b1d0fff2f4",
          "md5": "6b2e28c00fd369a2abcfa604a98ba892"
        }
      ]
    }
  ]
}
